name       : python-mergedeep
version    : 1.3.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/m/mergedeep/mergedeep-1.3.4.tar.gz : 0096d52e9dad9939c3d975a774666af186eda617e6ca84df4c94dec30004f2a8
license    : GPL-2.0-or-later # CHECK ME
component  : programming.python
summary    : A deep merge function for
description: |
    A deep merge function for
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
